AzureServicesDemo/Controllers/FileStorageController.cs
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AzureServicesDemo.Models;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.WindowsAzure.Storage;

namespace AzureServicesDemo.Controllers
{
    public class FileStorageController : Controller
    {
        private readonly AzureStorageManager _azureStorageManager;
        private readonly TelemetryClient _telemetry = new TelemetryClient();

        public FileStorageController()
        {
            CloudStorageAccount cloudStorageAccount;
            if (CloudStorageAccount.TryParse(
                ConfigurationManager.ConnectionStrings["AzureStorage"].ConnectionString,
                out cloudStorageAccount))
            {
                _azureStorageManager = new AzureStorageManager(cloudStorageAccount);
            }

            _telemetry.InstrumentationKey = TelemetryConfiguration.Active.InstrumentationKey;
        }

        public ActionResult Index()
        {
            if (_azureStorageManager == null)
            {
                return View("NoStorageConfigured");
            }

            var listBlobItems = _azureStorageManager.GetBlobList();
            return View(listBlobItems.Select(l => l.Uri.AbsoluteUri).ToList());
        }

        [HttpPost]
        public ActionResult UploadFile()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    _azureStorageManager.UploadBlob(fileName, file);

                    _telemetry.TrackTrace(string.Format(CultureInfo.InvariantCulture, "Uploaded file {0}", fileName), SeverityLevel.Information);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

AzureServicesDemo/Views/Shared/_Layout.cshtml
@using System.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @{
        var instrumentationKey = ConfigurationManager.AppSettings["AppInsightsInstrumentationKey"];
    }
    @if (!string.IsNullOrWhiteSpace(instrumentationKey))
    { 
    <script type="text/javascript">
        
        var appInsights=window.appInsights||function(config){
        function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey: '@instrumentationKey'
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Azure Services Demo ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Scaling", "Scaling", "Home")</li>
                    <li>@Html.ActionLink("Awesome new feature", "AwesomeNewFeature", "Home")</li>
                    <li>@Html.ActionLink("File storage", "Index", "FileStorage")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>